#!/bin/bash

remoteHost remote-key-no-spaces-or-special-characters && {
  hostName="Your host name written however you want it to"
  sshKey=/path/to/your/private/key #(or only key file if in ~/.ssh)
  userName=remote-host-user
  address=remote-host-address
}
